services:
  redis-warmer:
    image: comments-api
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    # We only run sync if Redis is empty
    command: >
      sh -c "if [ $$(redis-cli -h redis EXISTS v:c) -eq 0 ]; then
               python manage.py sync_votes_to_redis;
             fi"

  redis:
    image: redis:8-alpine
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  db:
    image: postgres:18
    shm_size: 256m
    env_file:
      - .env
    volumes:
      - postgres_v18:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$DB_USER -d $$DB_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgbouncer:
    image: edoburu/pgbouncer:v1.25.2-p0
    env_file:
      - .env
    ports:
      - "6432:5432"
    depends_on:
      - db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -p 5432  -U $$DB_USER -d $$DB_NAME']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: comments-api
    expose:
      - "8002"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src/backend:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8002"

  test:
    image: comments-api
    profiles:
      - test
    environment:
      - DJANGO_SETTINGS_MODULE=comments.settings_test
    volumes:
      - ./src/backend:/app
    command: python manage.py test --parallel --keepdb --noinput

  api-locust:
    image: comments-api
    expose:
      - "8003"
    ports:
      - "8003:8003"
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=False
    depends_on:
      db:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src/backend:/app
    command: >
      gunicorn comments.wsgi:application
      --bind 0.0.0.0:8003
      --workers 4
      --threads 3
      --worker-class gthread
      --max-requests 1000
      --max-requests-jitter 50
      --keep-alive 5
      --timeout 30
      --error-logfile -

  nginx:
    image: nginx:1.31
    ports:
      - "8002:8002"
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/frontend/dist:/usr/share/nginx/html
      - ./src/backend/media:/app/media
      - ./src/backend/static:/app/static
    depends_on:
      - api

volumes:
  # Reference the manually created volume
  postgres_v18:
    external: true
