FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    python3 python3-pip python3-venv \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

COPY requirements/ /requirements/
RUN pip install --no-cache-dir -r /requirements/dev-frozen.txt

WORKDIR /app

EXPOSE 8002

CMD ["python", "manage.py", "runserver", "0.0.0.0:8002"]
