# Generated by Django 6.0.6 on 2026-06-22 13:02

import comments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_make_profile_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=comments.models.avatar_file_path),
        ),
        migrations.AddIndex(
            model_name='commentvote',
            index=models.Index(fields=['comment', 'user', 'vote'], name='comments_co_comment_b04993_idx'),
        ),
    ]
