# Generated by Django 6.0.6 on 2026-06-22 16:37

import comments.models
import django.db.models.deletion
from django.db import migrations, models


def migrate_attachments(apps, schema_editor):
    Comment = apps.get_model('comments', 'Comment')
    CommentAttachment = apps.get_model('comments', 'CommentAttachment')
    for comment in Comment.objects.all():
        if comment.file or comment.file_type:
            CommentAttachment.objects.create(
                comment=comment,
                file=comment.file,
                file_type=comment.file_type,
            )


def reverse_migrate_attachments(apps, schema_editor):
    CommentAttachment = apps.get_model('comments', 'CommentAttachment')
    CommentAttachment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to=comments.models.attachment_file_path)),
                ('file_type', models.CharField(blank=True, choices=[('image', 'Image'), ('text', 'Text file')], max_length=10, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='comments.comment')),
            ],
            options={
                'verbose_name': 'Comment Attachment',
                'verbose_name_plural': 'Comment Attachments',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(migrate_attachments, reverse_migrate_attachments),
    ]
