# Generated by Django 6.0.6 on 2026-06-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_add_comment_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='file_type',
        ),
    ]
