# Generated by Django 5.2.3 on 2026-06-23 08:13

from django.db import migrations


def create_profiles(apps, schema_editor):
    # We use apps.get_model to avoid importing the model directly.
    # This ensures the migration uses the version of the model at this point in time.
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('comments', 'Profile')

    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)

def reverse_profiles(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_remove_file_filetype'),
    ]

    operations = [
        migrations.RunPython(create_profiles, reverse_profiles),
    ]
