# Generated by Django 5.2.3 on 2026-06-25 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_create_profiles_for_existing_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='commentvote',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='vote_unique_user_comment', violation_error_message='You can change your vote, not vote twice.'),
        ),
    ]
