# Generated by Django 5.2.3 on 2026-06-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_alter_commentvote_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
