# Generated by Django 5.2.3 on 2026-06-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0011_migrate_attachments_to_comment_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="author_email",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="comment",
            name="author_username",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION sync_comment_author_info() RETURNS trigger AS $$
            BEGIN
                UPDATE comments_comment
                SET author_username = NEW.username, author_email = NEW.email
                WHERE profile_id IN (SELECT id FROM comments_profile WHERE user_id = NEW.id);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER trg_sync_user_info
            AFTER UPDATE OF username, email ON auth_user
            FOR EACH ROW EXECUTE FUNCTION sync_comment_author_info();
            """,
            reverse_sql="""
            DROP TRIGGER trg_sync_user_info ON auth_user; DROP FUNCTION sync_comment_author_info();
            """,
        ),
    ]
