# Generated by Django 5.2.3 on 2026-06-30 19:39

from django.db import migrations


def populate_denormalized_fields(apps, schema_editor):
    User = apps.get_model("auth", "User")
    for user in User.objects.all().iterator(chunk_size=5000):
        user.profile.comments.all().update(
            author_username=user.username,
            author_email=user.email,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0012_comment_author_email_comment_author_username"),
    ]

    operations = [
        migrations.RunPython(code=populate_denormalized_fields),
    ]
