# Generated by Django 5.2.3 on 2026-06-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0013_auto_20260630_1939'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(condition=models.Q(('parent_id__isnull', True)), fields=['author_email'], name='idx_comment_top_email'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(condition=models.Q(('parent_id__isnull', True)), fields=['author_username'], name='idx_comment_top_username'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(condition=models.Q(('parent_id__isnull', True)), fields=['id'], name='idx_comment_top_id'),
        ),
    ]
