# Generated by Django 5.2.3 on 2026-07-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0014_comment_idx_comment_top_email_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='idx_comment_top_email',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='idx_comment_top_username',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(condition=models.Q(('parent_id__isnull', True)), fields=['author_email'], include=('id',), name='idx_comment_top_email'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(condition=models.Q(('parent_id__isnull', True)), fields=['author_username'], include=('id',), name='idx_comment_top_username'),
        ),
    ]
